### PR TITLE
Drop old PHP versions

### PR DESCRIPTION
**Pull request by henriquemoody**
There is a lot of commits here, I suggest you to review by commits.

It would be better to merge this pull request in a 3.0 branch

### CODE REVIEW

**Comment by henriquemoody** [comment]
Hey, @sokil! Thanks for your review.

I suggested to drop the support for PHP 7.1 because it's lifecycle is very close, but I understand if you would like to keep the support for that version, so I reverted that change.

Regarding the type hints and the docblocks, I though you would like to have that, it's enforcement that many frameworks are using https://github.com/sokil/php-isocodes/pull/17/files#diff-6b216d983cf0a62e9c648934c5687456R15. The reasoning is, with PHP type hints there is no need to also keep the docblocks. Would you still want to keep them?

**Comment by sokil** [comment]
1) We use 7.1 in our production )))
2) Doc block comments may be useful for some static analyse tools, for automatic documnation rendering, and for visual separating methods. Symfony in their code style document require dock block: https://symfony.com/doc/current/contributing/code/standards.html.

**Comment by henriquemoody** [comment]
> Doc block comments may be useful for some static analyse tools

Static analyse tools, like PHPStan, PHPMD, interpret the type hints instead. When there is a docblock it does check if it matches, so in theory it gets more expensive when you have docblocks.

> for automatic documentation rendering

I think phpDocumentor should be able to render the type hints. Do you use it somewhere I can check?

> visual separating methods

Can you elaborate on that? I'm not sure what you meant.

> Symfony in their code style document require dock block: https://symfony.com/doc/current/contributing/code/standards.html.

I think Symfony code is not a good example, because they have a strong BC break policy and their code doesn't declare strict types nor type hints.

However, if you check the most modern libraries, or the ones that don't have suck strong BC break policy, you'll see they all use that standard:

- https://github.com/zendframework/zend-diactoros
- https://github.com/zendframework/zend-expressive
- https://github.com/lcobucci/jwt

Doctrine is also heading to that direction (https://github.com/doctrine/coding-standard/blob/master/lib/Doctrine/ruleset.xml#L331)

**Comment by henriquemoody** [comment]
Anyways, just let me know what would you like to do:

1) Keep the pull request as is
2) Keep the type hints and restore the docblocks
3) Remove the type hints and restore the docblocks

**Comment by sokil** [comment]
4) Will check new waves in open source soon and decide

**Comment by sokil** [comment]
Merged to branch 3.0 and master. Master now is working branch for latest version branch. Thank you

**Pull request merged**
